/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.batch.entity.User;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  /**
   * 
   * @param args
   */
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    User u = new User();
    u.setUsername("AA");
    System.out.println("Hello, " + u.getUsername());
  }
}
